name: Get Data Everyday

on: push
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Scraper
      run: |
        python main.py
    
    - name: Check for change
      id: git-status
      run: |
        git diff --exit-code || echo "::set-output name=changed::true"
      continue-on-error: true
    
    # Runs a set of commands using the runners shell
    - name: Push to origin master
      if: steps.git-status.outputs.changed == 'true'
      run: |
        echo start push
        git config --global user.name "DarniNishanth" "github-actions[bot]"
        git config --global user.email "dharninishanth@gmail.com" "github-actions[bot]@users.noreply.github.com"
        
        git add -A
        git commit -m $(date '+%Y-%m-%d')
        git push
